version: "3.9"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - share_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: webnhatro@qn.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - share_network
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    networks:
      - share_network
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - share_network

volumes:
  local_pgdata:
  pgadmin-data:
networks:
  share_network: